name: hour

services:
  db:
    image: postgres:latest
    container_name: postgres-db

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - hour_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-db
    ports:
      - "6379:6379"
    networks:
      - hour_network

volumes:
  postgres_data:
networks:
  hour_network:
    driver: bridge

