name: hour

services:
  db:
    image: postgres:latest
    container_name: postgres-db

    env_file:
      - .env.dev

    ports:
      - "${DB_PORT}:5432"
    networks:
      - hour_network
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: redis-db
    ports:
      - "6379:6379"
    networks:
      - hour_network

volumes:
  postgres_data:
networks:
  hour_network:
    driver: bridge

