spring:
  application:
    name: hour
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:.env.${spring.profiles.active}[.properties]


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /v3/swagger-ui
    operations-sorter: method
    display-request-duration: true
    doc-expansion: none
    persist-authorization: true

custom:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  jwt:
    validations:
      access: ${JWT_ACCESS_EXPIRATION:900000}
      refresh: ${JWT_REFRESH_EXPIRATION:604800000}
    payload:
      issuer: ${JWT_ISSUER:hour}
      subject-access-token: ${JWT_ACCESS_SUBJECT:access-token}
      subject-refresh-token: ${JWT_REFRESH_SUBJECT:refresh-token}
    secrets:
      app-key: ${JWT_APP_KEY:local-dev-jwt-secret-key-must-be-at-least-32-bytes}
      origin-key: ${JWT_SECRET_KEY:local-dev-origin-key}
